# Generated by Django 5.0.4 on 2024-04-08 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='correo',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
