# Generated by Django 5.0.4 on 2024-04-15 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_empleado_correo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=40)),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.empleado')),
            ],
        ),
    ]
