# Generated by Django 5.0.4 on 2024-04-15 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_prueba'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_empresa', models.CharField(max_length=30)),
                ('direccion_empresa', models.CharField(max_length=100)),
                ('telefono_empresa', models.CharField(max_length=10)),
                ('email_empresa', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ocupacion',
            fields=[
                ('id_ocupacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_ocupacion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Egresado',
            fields=[
                ('id_egresado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_egresado', models.CharField(max_length=30)),
                ('apellido_egresado', models.CharField(max_length=30)),
                ('direccion_egresado', models.CharField(max_length=100)),
                ('telefono_egresado', models.CharField(max_length=10)),
                ('email_egresado', models.EmailField(max_length=100)),
                ('estatus_egresado', models.BooleanField()),
                ('ocupacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.ocupacion')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudServicio',
            fields=[
                ('id_solicitud', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_solicitud', models.DateField()),
                ('perfil_solicitud', models.TextField()),
                ('estatus_solicitud', models.BooleanField()),
                ('id_usuario', models.CharField(max_length=20)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.empresa')),
                ('ocupacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.ocupacion')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estatus_detalle', models.BooleanField()),
                ('id_egresado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.egresado')),
                ('id_solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.solicitudservicio')),
            ],
        ),
    ]
